- src/internal/FillPlotter.zig
There may be situations where a polygon is incomplete (only 2 or less corners plotted). We can just drop these cases.
This will get unit tested with the rest of the work in #15.
> FillPlotter: drop incomplete polygons

- .github/workflows/test.yml
Using goto-bus-stop/setup-zig@v2.
This cuts the build time down by about 30s, and only needs to cache Zig itself.
> actions: switch to direct Zig

- spec/001_smile_rgb.zig
- spec/002_smile_rgba.zig
- spec/023_smile_alpha_mask.zig
- spec/main.zig
- src/export_png.zig
- src/internal/Painter.zig
- src/surface.zig
This moves `Surface` and `ImageSurface` to an unmanaged, infallible design:
* Allocators are no longer stored in the surface.
* Anything that needs an allocator (e.g., `init`, `deinit`, and `downsample`) requires the same allocator to be used across the lifetime of the surface, as you would expect with unmanaged patterns within Zig.
* The only function that returns an error now is `init`. Every other function has a well-defined failure mode. Particularly, `getPixel` will return null on out-of-bounds requests, and `setPixel` will no-op. Additionally every pixel is valid on a surface for `setPixel` and `paintPixel`, using `copySrc` now instead of `fromPixel` (essentially making mismatched pixel types a cast).
Additionally, `ImageSurface` has gotten an `initBuffer` initializer. Using this …
> Surface: move to unmanaged and infallible design

- src/Context.zig
- src/internal/Painter.zig
- src/internal/PolygonList.zig
This removes the configurable FBA for the edge cache, moving it to a fallback allocator instead, with the FBA being a much smaller size, so that we respect the stack a lot more.
The FBA should be enough for 64 edges worst-case scenario each edge is 4 bytes and may be duplicated in the final edge set, so 64*4*2 = 512 bytes. Note that not all edges make it into the final edge set (e.g., during non-zero fill), hence why we say worst-case. This can and will be optimized eventually to allow for more.
> internal/Painter: remove configurable edge FBA, use fallback alloc

- src/Context.zig
- src/painter.zig
- src/pattern.zig
The `Pattern` improvments are trivial, so I'm just documenting the text from b77320bd7b472c2e156782ed5828c13b5443dcb4 here:
This makes the public painter interfaces public, and setting them up so that they can be used in an unmanaged way.
The idioms of the new `fill` and `stroke` operations are set up so that take take a required `Allocator`, `Surface`, `Pattern`, and `Nodes` to plot. Additionally, an options struct is supplied to both which contain optional arguments for both operations, with defaults that are in line with what is currently available to both in the `Context`. This allows for default behavior of these various operations should the user wish to do so.
> painter: public interface and small pattern tweaks

- build.zig
- build.zig.zon
- spec/main.zig
This adds Tracy profiler support into the acceptance tests.
We will likely keep Tracy out of the main library just to ensure it's not polluted by profiler code, unless people ask for it, and/or if pluggable profiler support gets added to Zig itself.
> Add Tracy profiler support into acceptance tests

- src/internal/FillPlotter.zig
- src/internal/Pen.zig
- src/internal/StrokePlotter.zig
- src/painter.zig
There were a couple of ArrayLists that were set up to be managed that didn't need to be, mainly in tests but also in Pen. This has been fixed now.
Also removed Pen.verticesFor as we are not using it, requires allocation, and we were storing the allocator for it - oops!
> internal: move all ArrayLists to be unmanaged

- build.zig
- build.zig.zon
- spec/main.zig
This makes Tracy a lazy dependency so that neither zig-tracy nor the Tracy source are pulled in  when they're not needed (normal use of the library, running unit tests, running E2E tests with Tracy disabled).
Some conditional importing and code adjustments needed to be made to the E2E tests to make this happen to ensure that zig-tracy was only imported when it was going to be available.
> Make Tracy Profiler a lazy dependency

- src/internal/Dasher.zig
- src/internal/dashed_plotter.zig
- src/internal/stroke_plotter.zig
There was an issue in the validation logic that would have allowed the full-zero case to go through. This has now been fixed (there has to be at least one greater-than-zero element present in order to be valid, with no negative values).
The validation logic has also been spun off from init so that the dasher is initialized in the dash plotter versus the generic stroke plotter. This was a minor issue that I missed fixing before 0.5.0 - it should avoid a minor amount of stack overhead and a copy, not a huge deal, but these are things I'm trying to be more cognizant of going forward.
> Dasher: fix/spin off validation logic

- spec/023_smile_alpha_mask.zig
- src/compositor.zig
- src/painter.zig
- src/pixel.zig
- src/surface.zig
- src/z2d.zig
This commit introduces some major changes to the compositor. This is ahead of work that will be happening to introduce extra compositor operations, including over a dozen or so blend modes - this makes the current implement-everything-with-boilerplate approach to composition operations untenable.
This requirement has allowed us to do a review of how we are doing the compositor, which has actually allowed us to greatly improve performance - approximately 20% non-AA, and **over 40% on default AA** for fill on RGBA surfaces (tested on a Zen3+ CPU w/AVX2). This latter case (AA on RGBA or RGB) also no longer requires an intermediary surface for its in (previously dstIn) operator, adding RAM savings onto the optimizations as well.
The summary of the changes:
* A new "compositor" package has …
> Compositor overhaul, introduce strides

- spec/059_stroke_star_gradient.zig
- spec/060_ghostty_logo.zig
- spec/061_linear_gradient.zig
- spec/062_hsl_gradient.zig
- spec/063_radial_gradient.zig
- spec/064_radial_source.zig
- spec/065_conic_gradient.zig
- spec/066_conic_pie_gradient.zig
- spec/067_gradient_transforms.zig
- spec/068_gradient_deband.zig
- spec/069_gradient_dither_context.zig
- src/Context.zig
- src/Dither.zig
- src/compositor.zig
- src/gradient.zig
- src/internal/util.zig
- src/painter.zig
- src/pattern.zig
- src/z2d.zig
This unifies all three gradient types under a single interface, which then is passed to the `Surface` union.
This makes things a bit easier under the hood for us, since we don't need to do a bunch of `inline else` statements for things that take gradients (dither patterns, compositor parameters, etc).
I've tried to make the interface intuitive, there's some wordy parts because we don't use tuples like in `Color.InitArgs`, but it also helps us document gradients at the top level.
> gradient: unify all gradient types

- src/Dither.zig
- src/color.zig
- src/compositor.zig
- src/export_png.zig
- src/gradient.zig
- src/internal/color_vector.zig
- src/internal/pixel_vector.zig
- src/internal/util.zig
At long last, we are nearing the release of 0.6.0!
This PR just does some housekeeping, namely on the `color` package. I'm removing all of the vector functionality out for the time being and making it internal. This was supposed to be internal for the most part anyway, but I had to expose a bunch of it as we needed it in the compositor.
Aside from this, there's just some minor bits like consolidating some uses of RGBA16 vectors and helper cleanup.
> Pre-release API cleanup

- src/surface.zig
This ensures that some dimensions that were not widened during compositing and surface allocation (`ImageSurface` allocation particularly) are now properly done.
Note that this was (unintentionally) limiting memory that could be allocated for `ImageSurfaces` to ~2GB, and now this limitation is gone, so folks should understand that and be careful. :slightly_smiling_face: 
Note that in applications where this is likely to come up (rendering large surface areas with AA), there's likely improvements that can be made here, although they are outside the scope of this small fix.
> surface: ensure ImageSurface.init alloc correctly widens dimensions

- src/internal/Polygon.zig
Every now and then we catch a degenerate case that generates NaN/Inf point values, which are currently a bit hard to track down because they're usually caught during rasterization, when the floating-point value is cast to integer. By this point, the polygon is fully "built" and the exact point where it happens is lost.
Hence, this is being added just as a safety/debugging catch-all to make sure no NaNs/Infs make it into a polygon at plot-time, which should make these cases easier to track.
> Polygon: assert on finite points on plot and plotReverse

- src/surface.zig
We currently only enforce a limitation on size dimensions when specifying surface.init and others to ensure non-negative values do not get provided. However, it's still possible to provide a zero to height or width, and get a zero-length surface, with some odd characteristics (namely, one of height or width will be non-zero).
To ensure correctness here, we're now enforcing that dimensions need to be positive, non-zero numbers.
> surface: disallow zero-size dimensions

- src/internal/PolygonList.zig
- src/painter.zig
- src/z2d.zig
This is the start of some validation work that I am undertaking to make sure edge cases are better validated against.
The first one is a fairly simple one in that we now will check to make sure that a polygon actually lies within the surface in some respect (in full, or overlapping) before drawing. Not only does this provide better protection against these kinds of cases, it skips unnecessary work in some cases, like in the event the polygon is adequately y-aligned but still outside on the x-axis.
> painter: validate that polygon lies within surface before compositing

- src/internal/Pen.zig
- src/internal/arc.zig
- src/internal/color_vector.zig
- src/internal/dashed_plotter.zig
- src/internal/fill_plotter.zig
- src/internal/stroke_plotter.zig
* Cleans up some use of unsigned variables when they are unnecessary or should not be used. This is reflective of a more general move away from usize and unsigned vars in general.
* Moves some stuff away from while loops to for loops, and removes some unnecessary fields in iterators as well.
* Also corrects a bug in an edge case catcher in `arc_max_angle_for_tolerance_normalized`, looks like when this was ported over from Cairo, we forgot to negate the testing clause in a `do..while` loop, now that this is a for loop it was a lot easier to catch as being bad. This is not getting hit in our normal test cases which is probably why it got missed.
> internal: usize/unsigned cleanups, arc bugfix

- src/compositor.zig
- src/export_png.zig
- src/painter.zig
- src/pixel.zig
- src/surface.zig
This is just the public version of #114, following on the new policy of:
* Avoiding unsigned integers whenever possible
* When conversions between unsigned to singed values need to be done, use coercion versus casting (this ensures comptime validation that our conversions will fit).
Note that, funny enough, there's a there's more spots in the public code where we can't avoid `usize` or casting. This is because a lot of the composition code which requires indexing into memory or conversion of pixel data is pretty much self-contained in their respective files. This work gets us in a good spot though to ensure anything that does come from a signed integer value is appropriately sanitized.
> Public int cleanups

- src/surface.zig
Compiling to a 32 bit target gave errors like:
```bash
src\surface.zig:681:23: error: expected type 'usize', found 'u63'
self._set(@max(0, @as(i64, self.width) * y + x), T.fromPixel(px));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src\surface.zig:681:23: note: unsigned 32-bit int cannot represent all possible unsigned 63-bit values
src\surface.zig:769:54: note: parameter type declared here
fn _set(self: *PackedImageSurface(T), index: usize, value: T) void {
```
By using `isize` it allows larger buffer sizes on targets that support it but limit the size on 32 bit targets
This was noticed in https://github.com/david-vanderson/dvui/pull/301 where we have a wasm32 target that failed.
> surface: use isize to allow for conversion to usize on 32bit targets

- src/internal/Polygon.zig
When calculating, the x-edges returned by the (previously named) `edgesForY` method would be clamped to `i30` (or should have been, after reviewing the code I'm not too sure if this would have actually worked). This is because we store the edges in a small stack-based buffer (512 bytes) that also includes the direction, and we want to make sure that there is enough room for 16 items here so these values are packed. However, the clamping was lost in #128.
This re-introduces it and ensures that the clamping happens correctly before conversion, which was the thing that was not happening even before #128. A unit test is also added that will trigger safety-checked UB if the clamping is not happening.
> Polygon: re-introduce xEdgesForY i30 clamping

- src/painter.zig
Short and sweet, just activates MSAA as the new default anti-aliasing method, replacing SSAA.
> painter: MSAA is the new default anti-alias method

- src/Path.zig
This commit lowers our path co-ordinate limit to `i24` - meaning that any co-ordinate set using `moveTo`, `lineTo`, etc., will now be limited to +/-8388608.
This is something I've mulled on and off for probably as long as z2d has existed, mainly as a measure of ensuring safety in the event of changes to accommodate things like fixed-point, which has never materialized as being necessary or useful, although this may change and has not been completely exhausted as a possibility.
Before this, the limit was `i32`, which was mainly serving as a upper limit of what could ultimately be returned in the event of drawing when no anti-aliasing was being done. However, anti-aliasing *does* effectively reduce the reasonable range to +/-536870912, and the advent of MSAA raises the possibility that we …
> Path: lower co-ordinate limit to i24

- src/Context.zig
This is a 2-part commit:
* First off, font was not being released on `deinit`, this is fixed now.
* Second off, we're correcting behavior for `deinit`, we set the underlying path to `undefined` but otherwise leave a lot of other stuff in place. This completely invalidates the context to `undefined` now, a pattern we will adopt later in the rest of the codebase.
> Context: release font on and fully invalidate on deinit

- src/Font.zig
- src/Path.zig
- src/gradient.zig
- src/internal/Glyph.zig
- src/internal/Pen.zig
- src/internal/Polygon.zig
- src/internal/sparse_coverage.zig
- src/surface.zig
The correct `deinit` convention should be: release resources, invalidate memory. We are currently not following the latter part of that convention. This fixes that, and sets the expectation for future `deinit` calls. :slightly_smiling_face: 
Note that there's `Context.deinitFont` that does a "pseudo-invalidation" - I've considered renaming this function (briefly, while I'm typing this :stuck_out_tongue_winking_eye:), and I think it's fine as-is. It *can* be considered an invalidation as it sets the in-use font to `.none`, which makes using text functions invalid until another font is set. That's following the spirit of the convention, as far as I'm concerned.
> Make deinit calls more strict/correct

- src/Context.zig
This type was going to be used as part of a combined `setFont` API, but I opted for the individual `setFontToFile` and `setFontToBuffer` calls instead.
> Context: remove unused SetFontSource

- src/pixel.zig
- src/surface.zig
This removes `copyStride` from the pixel package, in addition to other related unused functionality. This was alluded to be being planned in test comments in 158a006aec055dc11b5c271cc7e0a10917762808, meaning I was planning on doing it pretty much right after. ;)
Also adds a test for OOB index `getStride` (made coverage for surfaces more green).
> pixel: remove copyStride and other unused code
